title: yvesbd
subtitle: Test Github Pages

twitter_username: yvesbd
github_username:  yvesbd

email: yvesbd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Test GH pages description
baseurl: "/testghpages" # the subpath of your site, e.g. /blog
url: "https://yvesbd.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#theme: jekyll-theme-hacker
#theme: jekyll-dash
remote_theme: bitbrain/jekyll-dash
plugins:
  - jekyll-feed
  - jekyll-paginate
  - liquid-md5
  - jekyll/tagging


# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# wether the author box should be displayed
show_author: true

# the animation speed of the scroll-in effect
animation_speed: 50

# wether to enable Right-to-Left support or not
rtl: false

dash:
#  date_format: "%b %-d, %Y"
  date_format: "%Y-%m-%-d"


#  disqus:
#    shortname: <your-discuss-shortname>

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/yvesbd
      icon: twitter-square
      color: cyan
#    - url: https://bitbrain.itch.io
#      icon: itch-io
#      color: red
    - url: https://github.com/yvesbd
      icon: github-square
      color: purple      
