title: yvesbd
subtitle: Test Github Pages

twitter_username: yvesbd
github_username:  yvesbd

#theme: jekyll-theme-hacker
theme: jekyll-dash

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

dash:
#  date_format: "%b %-d, %Y"
  date_format: "%Y-%m-%-d"


#  disqus:
#    shortname: <your-discuss-shortname>

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/yvesbd
      icon: twitter-square
      color: cyan
#    - url: https://bitbrain.itch.io
#      icon: itch-io
#      color: red
    - url: https://github.com/yvesbd
      icon: github-square
      color: purple      
