title: yvesbd
subtitle: Test Github Pages

twitter_username: yvesbd
github_username:  yvesbd

email: yvesbd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Test GH pages description
baseurl: "/testghpages" # the subpath of your site, e.g. /blog
url: "https://yvesbd.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#theme: jekyll-theme-hacker

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# jekyll-tagging (optional)
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
